### ISSUE TITLE
Parse error: syntax error, unexpected T_FUNCTION in ... /assets/plugins/managermanager/widgets/ddselectdocuments/ddselectdocuments.php on line 125

### ISSUE THREAD

**Issue by MrSwed** [DivanDesign/EvolutionCMS.plugins.ManagerManager#1]
PHP Version 5.2.17

Parse error: syntax error, unexpected T_FUNCTION in ... /assets/plugins/managermanager/widgets/ddselectdocuments/ddselectdocuments.php on line 125

**Comment by psthmn** [comment]
Hi there! We already know about the problem. You can see the fix here (https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager/commit/1c203532a3faac36fcf03925cf47be44c0676ed8). 0.6.1 coming soon.
