### ISSUE TITLE
yams tabs breaks after upgrade 1.0.14 -> 1.0.15

### ISSUE THREAD

**Issue by fourroses666** [DivanDesign/EvolutionCMS.plugins.ManagerManager#11]
I think ManagerManager breaks the YAMS tabs after upgrade.
https://github.com/modxcms/evolution/issues/367#issuecomment-63309562

I have made a test site where you can see the tabs are all on the main tab and not country tabs.
MAybe you can have a look at it?

I can e-mail you login.

**Comment by Ronef** [comment]
Hi! I'm sorry, but I have no time right now =( How about this weekend? If this is ok, please, text me on Skype (ilyasRonef).

**Comment by fourroses666** [comment]
ok cool

**Comment by Jako** [comment]
Deesen has found a solution: https://github.com/modxcms/evolution/issues/367#issuecomment-63801153

Maybe you could look into that?

**Comment by fourroses666** [comment]
Hi Ronef, seen my message on skype?

**Comment by Ronef** [comment]
@Jako, I think YAMS must be fixed instead of using Deesen's solution. Obviously, it's deprecated and evaluates some redundant code in each MM call.

**Comment by Jako** [comment]
I don't maintain YAMS and I have no time to fix that in YAMS.

Think it is caused somewhere in [YAMS mm_rules](https://github.com/goldsky/YAMS/blob/master/yams.mm_rules.inc.php)

Will push Deesen in the right direction.

**Comment by fourroses666** [comment]
I have a fix but MM needs to change a small thing.

I think MM needs to add $mm_version = mm_version(); or something to let this work :)
And yams.module.funcs.inc.php needs to change some lines asswell:

line 70:

```
else
{
  if ( is_null( $mmVersion ) )
  {
    // new style references
    return $prefix . $id;
  }
  // If a managermanager version has been specified, then
  // the output depends on the version...
    if ( version_compare( $mmVersion, '0.3.4', '<' ) )
    {
        // Older versions of managermanager required an id
        return $prefix . $id;
    }
    else if ( version_compare( $mmVersion, '0.6.2', '<' ) )
    {
        // but newer versions require a name...
        return $prefix . $name;
    }
    else
    {
        // and even newer versions don't accept the prefix...
        return $name;
    }
}
```

**Comment by fourroses666** [comment]
YAMS pluginfile: `yams.mm_rules.inc.php`

Add the following line:

// Temporarily hardwiring it for test purposes...
// Yes, this works... So, to fix this properly, the MM people will need to explain how to access the MM version from within the mm rules file.
`$mm_version = '0.6.2';`

**Comment by fourroses666** [comment]
It has been determined that one of the reasons YAMS is not working with MM 0.6.2 is as follows: Previously, a variable called $mm_version containing the MM version number was accessible from within the mm_rules chunk/file. YAMS was using thing to allow backwards compatibility with older versions of MM. It appears that this variable is no longer defined. Please could you provide instructions for how to access the ManagerManager version number from within the mm_rules file? Perhaps there is a method called mm_version(), which returns the version number? If not, perhaps you could add one? Thank you.

**Comment by Ronef** [comment]
@fourroses666 Marc, try `global $mm_version;`.

**Comment by fourroses666** [comment]
in the mm_rules? I'm a bit confused :confused:

**Comment by fourroses666** [comment]
@Ronef , Can you please explain where to add this global $mm_version; (PHP isn't a language I speak :-P) This needs to be fixed for the next version :+1:
