### ISSUE TITLE
when saving resource I see error on this host

### ISSUE THREAD

**Issue by fourroses666** [DivanDesign/EvolutionCMS.plugins.ManagerManager#14]
![mm-error](https://cloud.githubusercontent.com/assets/523389/5474617/063c599e-8613-11e4-91d1-4606f7688464.png)

**Comment by fourroses666** [comment]
line 22 and 50 are empty.

the line befor them are:
21: $mm_version = '0.6.2'; 
49: $pluginDir = $modx->config['base_path'].'assets/plugins/managermanager/';

Looks like everything is working thow.
Any idea whats wrong?

**Comment by Jako** [comment]
'<?php' in plugin code?

**Comment by fourroses666** [comment]
The ManagerManager plugin "content" doesn't have the <?php code, just;
include($modx->config['base_path'].'assets/plugins/managermanager/mm.inc.php');

The error messages are getting bigger when having more resources.

![weird](https://cloud.githubusercontent.com/assets/523389/5486448/0053610a-86a7-11e4-8fc4-fbc57f7f3227.jpg)

Or could there be some DB problem going on here?

**Comment by fourroses666** [comment]
oké seems to do with my mm_rules!
it doesn't like this:

`if($content['parent'] == 5){
  mm_moveFieldsToTab('media-afb', 'extra');
}`

`if($content['parent'] != 5){
  mm_hideFields('media-afb');
}`

Same here:
https://github.com/dmi3yy/modx.evo.custom/issues/98

**Comment by fourroses666** [comment]
Gona try:
http://stackoverflow.com/questions/15361392/how-do-i-correct-this-illegal-string-offset

if ($content['parent'] == '5') {
if (is_array($content) && $inputs['parent'] == '5') {

**Comment by fourroses666** [comment]
When changing: 
`if($content['parent'] == 5){`

to:
`if (is_array($content) && $content['parent'] == '5') {`

no more errors.

is there some code deleted in MM or something :hammer:

**Comment by Ronef** [comment]
This is not ManagerManager issue.
