### ISSUE TITLE
Cannot read property 'hasChildNodes' of undefined

### ISSUE THREAD

**Issue by fourroses666** [DivanDesign/EvolutionCMS.plugins.ManagerManager#17]
When I use this rule in MM_rules: (to get on page Evogallery upload tab)
mm_widget_evogallery('2','','','7');

In Firefox IE there is no problem but in Chrome I get:

ManagerManager: An error has occurred: TypeError - Cannot read property 'hasChildNodes' of undefined

and all mm_rules stop working.

Evo 1.0.14
MM 0.6.1

**Comment by Ronef** [comment]
Oh, “mm_widget_evogallery” is not included in the “ManagerManager” plugin, so we can't help you. Try to find “mm_widget_evogallery” developers.

**Comment by fourroses666** [comment]
*Works on 1.0.15 and MM 0.6.2 :+1:

**Comment by Ronef** [comment]
Not Bad =)

**Comment by fourroses666** [comment]
Hmmm, it don't work :( 

(I think when checked I used an other browser..)
