### ISSUE TITLE
if($content['parent'] != 30 || $content['parent'] != 31) {

### ISSUE THREAD

**Issue by fourroses666** [DivanDesign/EvolutionCMS.plugins.ManagerManager#19]
works:
if($content['parent'] == 30 || $content['parent'] == 31) {
    mm_widget_evogallery('5','Fotoboek','','');
}
(visible on all parent of 30 and 31 :+1: )

Doesn't work:
if($content['parent'] != 30 || $content['parent'] != 31) {
    mm_widget_evogallery('5','Fotoboek','','');
}
(visible on all resources :-1: )

is it a bug when using != ?

**Comment by fourroses666** [comment]
http://forums.modx.com/thread/96805/mm-rules-parent-30-and-31

**Comment by Ronef** [comment]
How can the ”!=” operator not work in ManagerManager? O_o Or I misunderstood something?

**Comment by Ronef** [comment]
This code was written in a chunk or file?

**Comment by fourroses666** [comment]
hi Ronef, this is in the chunk mm_rules.

latest evo 1.0.15

**Comment by Segr** [comment]
!($content['parent'] == 30 || $content['parent'] == 31) => ($content['parent'] != 30 && $content['parent'] != 31)

**Comment by fourroses666** [comment]
going to test that tomorrow thx :)

**Comment by Ronef** [comment]
))))))))))))))))))))))

**Comment by fourroses666** [comment]
It works! thanks Segr

example:
`if ($content['parent'] != 30 && $content['parent'] != 31){
    mm_hideFields('introtext');
}`

**Comment by fourroses666** [comment]
This doesn't work, when using 2x parent !=1

if($content['parent'] != 1{
    mm_hideFields('foto');
}

if ($content['parent'] != 1 && $content['id'] != 18){ 
    mm_hideFields('videolink'); 
}

**Comment by Segr** [comment]
Ronef, close it.
This is not a school of programmers.

**Comment by fourroses666** [comment]
Its already closed..
