### ISSUE TITLE
mysql_* функции

### ISSUE THREAD

**Issue by AgelxNash** [DivanDesign/EvolutionCMS.plugins.ManagerManager#2]
в файле utilites есть как минимум 1 вызов функции mysql_\* функции использование которой сделает плагин не рабочим (точнее сделает не рабочим экранирование текста) при переходе на PDO\MySQLi. Поэтому лучшим вариантом будет использование метода DBAPI:escape();

**Comment by Ronef** [comment]
Всё верно, сделаем (или можешь сам сделать и отправить запрос ;-).
