### ISSUE TITLE
Translation Bug ddMultipleFields Widget

### ISSUE THREAD

**Issue by iAmKrug** [DivanDesign/EvolutionCMS.plugins.ManagerManager#20]
ddMultipleFields widget always shows as "Вставить" for the file or image "insert" text regardless of the language.

jquery.ddMM.mm_ddMultipleFields.js
Line 244

[Screenshot of Bug](http://bravotangolaboratory.ca/screenshot/ManagerManager-example.png)
[Screenshot of Code](http://bravotangolaboratory.ca/screenshot/ManagerManager-code-example.png)

**Comment by Ronef** [comment]
Hi! Thanks, “mm_ddMultipleFields” has its own repository: https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddMultipleFields.

**Comment by iAmKrug** [comment]
Sorry, I moved this issue to the mm_ddMultipleFields repo

Thanks!
- Kyle
