### ISSUE TITLE
Баг с перемещенными полями 1.2-d8.1.5

### ISSUE THREAD

**Issue by Typodin** [DivanDesign/EvolutionCMS.plugins.ManagerManager#22]
При создании новой вкладки, с последующим созданием в ней новых секций и полей (типа так: http://joxi.ru/KAxVoqxI4zkDKm ) при первом открытии ресурса после создания или после создания нового документа все поля недоступны для редактирования. После пересохранения страницы все кроме RichText работает.

В предыдущей версии баг отсутствует.

Баг наблюдаю в Chrome. Mozilla работает нормально.

Также после создания нового таба периодически валится ошибка: http://joxi.ru/DmBnLjyuNVbepm Закономерностей в появлении не нашел, бывает что заходишь нормально, а иногда ошибка. Тоже Crhome, в Mozilla все ок.

**Comment by Ronef** [comment]
1. Пробовали ManagerManger из ветки `develop`?
2. Создайте пожалуйста отдельный issue по второму багу.

**Comment by Typodin** [comment]
Судя по всему были внесены правки в сборку, так как после обновления данного проекта и при работе с новыми проблема исчезла.
