### ISSUE TITLE
mm_hideFields('tv_checkbox') - Syntax error unrecognized expression

### ISSUE THREAD

**Issue by MrSwed** [DivanDesign/EvolutionCMS.plugins.ManagerManager#6]
Syntax error unrecognized expression: input[name=tv25[]]
To fix add quotes in [name=**'value'**]:
assets/plugins/managermanager/widgets/mm_hidefields/mm_hidefields.php
line 75

```
$output .= '$j("'.$mm_fields[$field]['fieldtype'].'[name=\''.$mm_fields[$field]['fieldname'].'\']").parents("tr").hide().next("tr").find("td[colspan=2]").parent("tr").hide(); ';
```

IMHO, all attribute selectors should have quotes not only this
http://api.jquery.com/category/selectors/attribute-selectors/

**Comment by MrSwed** [comment]
Fix for mm_hidefields.php
https://github.com/MrSwed/MODXEvo.plugin.ManagerManager/commit/d8b84c7f5c7b7fa019e7a1e36f5e87f2595592ec

**Comment by Ronef** [comment]
This issue makes sense. Please, create a pull request to https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_hideFields.
